services:
  backend:
    env_file:
      - .env.production
    command: npm run start:production --workspace backend
    environment:
      NODE_ENV: production
    ports:
      - "${BACKEND_HOST_PORT:-4301}:3000"

  frontend:
    env_file:
      - .env.production
    environment:
      NODE_ENV: production
    ports:
      - "${FRONTEND_HOST_PORT:-4302}:3000"

  nginx:
    volumes:
      - nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
      - nginx/conf.d/prod.conf:/etc/nginx/conf.d/env.conf:ro
    ports:
      - "${NGINX_HOST_PORT:-80}:80"
    restart: unless-stopped
