import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import type { ReactElement, ReactNode } from "react";

import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface IRootLayoutProps {
  readonly children: ReactNode;
}

// Next.js mandates the children prop shape; disable-readonly rule here keeps JSX ergonomic.
 
const RootLayout: (props: Readonly<IRootLayoutProps>) => ReactElement = (props) => {
  const { children } = props;

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
};

export default RootLayout;
